### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by ily-iskandar** [PenangScienceCluster/virus-hunter-website#1]
![image](https://user-images.githubusercontent.com/92915738/138239476-ae9d1fc0-209a-4cf9-ac1b-b988168cd3d8.png)

Add a period at the end of "Pilih bingkai kegemaran anda dibawah".

**Comment by chanjuping** [comment]
Fixed after tidying up a bit of the codebase.
![image](https://user-images.githubusercontent.com/38552313/142128378-f5556cc9-143f-4172-9233-387bea7fcbcb.png)
